# This is a basic workflow to help you get started with Actions

name: Automated API tests using Postman CLI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl https://dl-cli.pstmn-stage.io/download/latest/linux/ -o postman-cli.tar.gz
          tar -zxvf postman-cli.tar.gz
          sudo mv postman-cli /usr/bin/postman
          rm postman-cli.tar.gz
      # Runs a single command using the runners shell
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-631ef70dc9bab0003c5cf312-7db4453acc9f884f3a2340426c3241cb20
      - name: Run API tests
        run: |
          export POSTMAN_API_BASE_URL='https://api.getpostman-stage.com'
          postman collection run "${GITHUB_ACTION_PATH}/postman/collections/Postman API reference.json" --integration-id "127168-${GITHUB_JOB}"
          # Run your API using Postman CLI
          postman api lint --integration-id=127168
